AGR: './data/data-sheet-agriculture.xlsx'
BLD: './data/data-sheet-buildings.xlsx'
IND: './data/data-sheet-industry.xlsx'
NON: './data/data-sheet-nonspecified.xlsx'
OWN: './data/data-sheet-ownuse.xlsx'
PIP: './data/data-sheet-pipeline transport.xlsx'
TRN: './data/data-sheet-transport.xlsx'
DEM: './data/my-demands.xlsx'
HYD: './data/data-sheet-hydrogen.xlsx'
POW: './data/data-sheet-power.xlsx'
REF: './data/data-sheet-refining.xlsx'
SUP: './data/data-sheet-supply.xlsx'
XXX: './data/data-sheet-xxx.xlsx'
YYY: './data/data-sheet-yyy.xlsx'